[package]
name = "b"
version = "2024.10.31"
edition = "2024"
description = "test asc workspace member b"
license = "LGPL-3.0-or-later"
repository = ""
branch = "main"

[[bin]]
name = "bbin"
source_dir = "src"
source_file = "main.cpp"

[[lib]]
name = "b"
source_dir = "src"
source_file = "lib.cpp"
shared = false

[features]

[dependencies]
spdlog = { version = "1.14.1", find_packages = ["spdlog"], include_directories = [], link_libraries = ["spdlog::spdlog"], features = [] }
