[package]
name = "b"
version = "2024.10.31"
edition = "2024"

[[bin]]
name = "bbin"
path = "src/main.cpp"

[[lib]]
name = "b"
path = "src/lib.cpp"
shared = false

[features]

[dependencies.spdlog]
version = "1.14.1"
find_packages = ["spdlog"]
link_libraries = ["spdlog::spdlog"]
features = []
