[package]
name = "a"
version = "2024.10.31"
edition = "2024"
description = "test asc workspace member a"
license = "LGPL-3.0+"
repository = ""

[[bin]]
name = "abin"
source_dir = "src"
source_file = "main.cpp"

[[lib]]
name = "a"
source_dir = "src"
source_file = "lib.cpp"
shared = false

[features]

[dependencies.cli11]
version = "2.4.2#1"
find_packages = ["CLI11"]
link_libraries = ["CLI11::CLI11"]
features = []
