[package]
name = "test_source_parser"
version = "2024.11.29"
edition = "2021"

[dependencies]
c_source_parser_ffi = { version = "2024.11.29", path = "../c_source_parser_ffi" }
rs_container_ffi = { version = "2024.11.29", path = "../rs_container_ffi" }
walkdir = { version = "2.5.0" }

