[package]
name = "test_c_cpp"
version = "2024.10.30"
edition = "2024"

[features]

[dependencies.cli11]
version = "2.3.2"
find_packages = ["CLI11"]
link_libraries = ["CLI11::CLI11"]
features = []

[dependencies.fmt]
version = "10.0.0"
find_packages = ["fmt"]
link_libraries = ["fmt::fmt"]
features = []

[dependencies.spdlog]
version = "1.11.0#1"
find_packages = ["spdlog"]
link_libraries = ["spdlog::spdlog"]
features = []
