[package]
name = "a"
version = "2024.10.31"
edition = "2024"

[[bin]]
name = "abin"
path = "src/main.cpp"

[[lib]]
name = "a"
path = "src/lib.cpp"
shared = false

[features]

[dependencies.cli11]
version = "2.4.2#1"
find_packages = ["CLI11"]
link_libraries = ["CLI11::CLI11"]
features = []
