[package]
name = "ast"
version = "2024.11.13"
edition = "2024"

[[lib]]
name = "ast"
path = "src/main.cpp"
shared = false

[features]

[dependencies]
# llvm = { version = "18.1.6#1", find_packages = ["clang"], link_libraries = ["clang"], features = ["clang"] }
