[package]
name = "ast"
version = "2024.11.20"
edition = "2024"
description = "scan necessary source files"
license = "LGPL-3.0+"
repository = ""
branch = "main"

[[lib]]
name = "ast"
source_dir = "src"
source_file = "lib.cpp"
shared = false
std_c = "11"
std_cxx = "17"

[dependencies]
fmt = { version = "11.0.2#1", find_packages = ["fmt"], include_directories = [], link_libraries = ["fmt::fmt"], features = [] }
llvm = { version = "18.1.6#1", find_packages = ["Clang"], include_directories = ["${CLANG_INCLUDE_DIRS}"], link_libraries = ["libclang"], features = ["clang"] }

[std_dependencies]
std_cxx = { name = "stdc++", check = "HAVE_STD_CXX_LIB"}
std_cxx_fs = { name = "stdc++fs", check = "NOT HAVE_CXX_FILESYSTEM_LIB"}
