[package]
name = "test_c"
version = "2024.11.9"
edition = "2024"
description = "pure c syntax code"
license = "LGPL-3.0-or-later"
repository = ""

[[bin]]
name = "test_c"
source_dir = "src"
source_file = "main.c"

[features]

[dependencies]
