[package]
name = "c"
version = "2024.10.31"
edition = "2024"

[[lib]]
name = "c"
path = "src/lib.cpp"
shared = true

[features]

[dependencies.fmt]
version = "11.0.2#1"
find_packages = ["fmt"]
link_libraries = ["fmt::fmt"]
features = []
