[package]
name = "config_file_derives"
version = "2024.11.1"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
proc-macro2 = { version = "1.0.89" }
quote = { version = "1.0.37" }
syn = { version = "2.0.85" }

