[package]
name = "test_package"
version = "2024.10.30"
edition = "2024"
description = "test asc package"
license = "LGPL-3.0-or-later"
repository = ""

[[bin]]
name = "test_package_bin"
source_dir = "src"
source_file = "main.cpp"

[[lib]]
name = "test_package_lib"
source_dir = "src"
source_file = "lib.cpp"
shared = true

[features]

[dependencies]
arrow = { version = "17.0.0", find_packages = [], link_libraries = [], features = ["json", "mimalloc@windows"] }
cli11 = { version = "2.3.2", find_packages = ["CLI11"], include_directories = [], link_libraries = ["CLI11::CLI11"], features = [] }
fmt = { version = "10.0.0", find_packages = ["fmt"], include_directories = [], link_libraries = ["fmt::fmt"], features = [] }
openssl = { version = "3.3.2#1", find_packages = ["openssl"], include_directories = [], link_libraries = ["OpenSSL::Crypto", "OpenSSL::SSL"], features = [] }
spdlog = { version = "1.11.0#1", find_packages = ["spdlog"], include_directories = [], link_libraries = ["spdlog::spdlog"], features = [] }
